---
title: "MAGMA Manual"
author: Julian Urban, Markus Feuchter, Vsevolod Scherrer, Moritz Breit, & Franzis
  Preckel
date: "2023-08-30"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 1
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  echo = TRUE)
```


# Balance_extract

Balance extraction


## Description

This function extracts the balance criteria or pairwise effects of a
 `Balance_MAGMA` result for a specified sample size.


## Usage

```r
Balance_extract(Balance, samplesize, effects = FALSE)
```


## Arguments

Argument      |Description
------------- |----------------
`Balance`     |     A result of Balance_MAGMA. Compare the function [`Balance_MAGMA`](#balancemagma) .
`samplesize`     |     An integer indicating the sample size for which the balance criteria or pairwise effects should be extracted.
`effects`     |     Indicates whether balance criteria or pairwise effects should be extracted. The default FALSE returns the balance criteria, while TRUE  leads to the extraction of the pairwise effects.


## Details

Based on a previous computed [`Balance_MAGMA`](#balancemagma) object this function
 enables the extraction of balance criteria or pairwise effects for each
 desired sample size. Thus, checking the balance for each possible sample size
 independently is possible.


## Value

Depends on effects argument. If FALSE it returns in a vector
 containing the balance criteria. If TRUE it returns a vector containing
 all possible pairwise effects.


## Author

Julian Urban


## Examples

```r
#Defining the names of the metric and binary covariates
covariates_vector <- c("GPA_school", "IQ_score", "Motivation", "parents_academic", "sex")

#Matching data set for giftedness support with exact matching for enrichment.
MAGMA_sim_data_gifted_exact <- MAGMA_exact(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
exact = "enrichment",
cores = 2)


#Estimating Balance
Balance_gifted_exact <- Balance_MAGMA(data = MAGMA_sim_data_gifted_exact,
group = "gifted_support",
covariates = covariates_vector,
step = "step") #step created during matching
str(Balance_gifted_exact)

#Balance criteria for a 100 cases per group
#Balance criteria
Balance_100_gifted <- Balance_extract(Balance = Balance_gifted_exact,
samplesize = 100,
effects = FALSE)
Balance_100_gifted

#Pairwise Effects
Balance_100_gifted_effects <- Balance_extract(Balance = Balance_gifted_exact,
samplesize = 100,
effects = TRUE)
Balance_100_gifted_effects

#Computing 2x2 Matching for giftedness support and enrichment equivalent to
#a four group matching
MAGMA_sim_data_gift_enrich <- MAGMA(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
dist = "ps_2x2",
cores = 2)


#Estimating Balance. Covariates same as above
Balance_2x2 <- Balance_MAGMA(data = MAGMA_sim_data_gift_enrich,
group = c("gifted_support", "enrichment"),
covariates = covariates_vector,
step = "step") #step created during matching
str(Balance_2x2)

#Balance criteria for a 125 cases per group
#Balance criteria
Balance_125_2x2 <- Balance_extract(Balance = Balance_2x2,
samplesize = 125,
effects = FALSE)
Balance_125_2x2

#Pairwise Effects
Balance_125_2x2_effects <- Balance_extract(Balance = Balance_2x2,
samplesize = 125,
effects = TRUE)
Balance_125_2x2_effects
```


# Balance_MAGMA

Balance estimation


## Description

This function computes all four Balance criteria of MAGMA, namely
 Pillai's Trace , d-ratio , mean g , and adjusted d-ratio . It can
 consider binary and metric variables for balance estimation. Balance
 Estimation is conducted over a varying sample size. See Details for more
 information.


## Usage

```r
Balance_MAGMA(Data, group, covariates, step = "step")
```


## Arguments

Argument      |Description
------------- |----------------
`Data`     |     A data frame containing at least the grouping variable, the step variable from the main MAGMA-function (or other matching algorithms), and all covariates of interest.
`group`     |     A character specifying the name of your grouping variable in data. Note that MAGMA can only match your data for a maximum of 4 groups. For matching over two groups (e.g., 2x2 Design) is possible by specifying group as a character vector with a length of two. In this case each or the 2 grouping variables can only have two levels.
`covariates`     |     A character vector listing the names of all binary and metric covariates of interest.
`step`     |     A character naming the step variable of the matching. Per default it specifies the name as step , which corresponds the resulting name of the main MAGMA function.


## Details

This function computes all four Balance criteria of MAGMA, namely Pillai's
 Trace, d-ratio, mean g, and adjusted d-ratio. This is an iterative process
 including more cases with each iteration according to the step variable.
 Thus, starting with cases having a small within match distance, larger
 distances are included with increasing iterations. As minimum the function
 specifies a n >= 20 per group. This does not imply, that balance criteria
 with such a small sample size can be estimated consistently. For Pillai's
 Trace a higher minimum sample size can be possible. It depends on the number
 of covariates to ensure a positive model identification.
 Missing data for Pillai's Trace are excluded listwise, while for the other
 balance criteria pairwise exclusion is applied.


## Value

A list of length four containing all balance criteria and all
 pairwise effects with respect to group sample size.


## Author

Julian Urban


## References

Pastore M., Loro P. A. D., Mingione M., & Calcagni A. (2022). overlapping: Estimation of Overlapping in Empirical Distributions. R package version 2.1. https://CRAN.R-project.org/package=overlapping")  
Revelle, W. (2023) psych: Procedures for Psychological, Psychometric, and Personality Research. Illinois.  https://CRAN.R-project.org/package=psych  
Viechtbauer, W. (2010). Conducting meta-analyses in R with the metafor package. Journal of Statistical Software, 36(3), 1-48. https://doi.org/10.18637/jss.v036.i03  
Fisher Z, Tipton E, Zhipeng H (2023).robumeta: Robust Variance Meta-Regression. R package version 2.1. https://CRAN.R-project.org/package=robumeta


## Examples

```r
#Defining the names of the metric and binary covariates
covariates_vector <- c("GPA_school", "IQ_score", "Motivation", "parents_academic", "sex")

#Matching data set for giftedness support with exact matching for enrichment.
MAGMA_sim_data_gifted_exact <- MAGMA_exact(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
exact = "enrichment",
cores = 2)


#Estimating Balance
Balance_gifted_exact <- Balance_MAGMA(Data = MAGMA_sim_data_gifted_exact,
group = "gifted_support",
covariates = covariates_vector,
step = "step") #step created during matching
str(Balance_gifted_exact)

#Computing 2x2 Matching for giftedness support and enrichment equivalent to
#a four group matching
MAGMA_sim_data_gift_enrich <- MAGMA(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
dist = "ps_2x2",
cores = 2)


#Estimating Balance. Covariates same as above
Balance_2x2 <- Balance_MAGMA(Dta = MAGMA_sim_data_gift_enrich,
group = c("gifted_support", "enrichment"),
covariates = covariates_vector,
step = "step") #step created during matching
str(Balance_2x2)
```


# Density_overlap

Kernel-Density overlap


## Description

This function shows and quantifies the kernel density overlap of a variable
 for two or more groups.


## Usage

```r
Density_overlap(
  Data,
  variable,
  group,
  variable_name = NULL,
  group_labels = NULL,
  group_name = NULL,
  step_num = NULL,
  step_var = NULL
)
```


## Arguments

Argument      |Description
------------- |----------------
`Data`     |     A data frame that contains the desired variable for density plotting as well as the specified grouping variable.
`variable`     |     A character naming the variable for that the density should be plotted.
`group`     |     A character specifying the groups for which the density should be plotted. Can be an independent group comparison (e.g., comparing matched groups) or the comparison of pre and post matched samples.
`variable_name`     |     A character specifying the name that should appear in the plot for variable.
`group_labels`     |     A character vector specifying the labels for the groups that should appear in the legend of the plot.
`group_name`     |     A character specifying the name of the grouping variable that should appear in the title of the legend.
`step_num`     |     An integer specifying the number of cases that should be included per group in this post matching comparison. Is based on the step variable of MAGMA.
`step_var`     |     A Character specifying the name of the step variable.


## Details

This function enables the comparison of the density of variables for two
 or more groups. It plots the kernel density separately for each group and
 quantifies the amount of overlap.


## Value

A Plot showing the kernel density for a specified variable separated
 for specified groups and the quantification of this overlap.


## Author

Julian Urban


## References

Pastore M., Loro P. A. D., Mingione M., & Calcagni A. (2022). overlapping: Estimation of Overlapping in Empirical Distributions. R package version 2.1. https://CRAN.R-project.org/package=overlapping


## Examples

```r
#Density overlap in Propensity scores for gifted before matching
Density_overlap(Data = MAGMA_sim_data,
variable = "ps_gifted",
group = "gifted_support",
step_num = NULL,
step_var = NULL,
variable_name = "Propensity Score",
group_labels = c("No Support", "Support"),
group_name = "Gifted Support")

#Density overlap in Propensity scores for gifted after matching with 250 cases per group.
Density_overlap(Data = MAGMA_sim_data_gifted,
variable = "ps_gifted",
group = "gifted_support",
step_num = 250,
step_var = "step",
variable_name = "Propensity Score",
group_labels = c("No Support", "Support"),
group_name = "Gifted Support")

#Density overlap in GPA for teacher ability rating before matching
Density_overlap(Data = MAGMA_sim_data,
variable = "GPA_school",
group = "teacher_ability_rating",
variable_name = "School Achievement",
group_labels = c("Low", "Medium", "High"),
group_name = "Rating")
```


# initial_unbalance

Initial unbalance estimation


## Description

This function computes all four Balance criteria of MAGMA, namely
 Pillai's Trace , d-ratiO , mean g , and adjusted d-ratio for the
 unmatched data set. This enables comparison of initial and after matching
 unbalance.


## Usage

```r
initial_unbalance(Data, group, covariates)
```


## Arguments

Argument      |Description
------------- |----------------
`Data`     |     A data frame containing at least the grouping variable and all covariates of interest.
`group`     |     A character specifying the name of your grouping variable in data. Note that MAGMA can only match your data for a maximum of 4 groups. For matching over two groups (e.g., 2x2 Design) is possible by specifying group as a character vector with a length of two. In this case each or the 2 grouping variables can only have two levels.
`covariates`     |     A character vector listing the names of all binary and metric covariates of interest.


## Details

This function computes all four Balance criteria of MAGMA, namely Pillai's
 Trace, d-ratio, mean g, and adjusted d-ratio for the overall samples. This
 leads to different sample sizes per group. Missing data for Pillai's Trace
 are excluded listwise, while for the other balance criteria pairwise
 exclusion is applied.


## Value

A numeric vector of length 4 containing the respective balance
 criteria for the unmatched sample.


## Author

Julian Urban


## References

Pastore M., Loro P. A. D., Mingione M., & Calcagni A. (2022). overlapping: Estimation of Overlapping in Empirical Distributions. R package version 2.1. https://CRAN.R-project.org/package=overlapping")  
Revelle, W. (2023) psych: Procedures for Psychological, Psychometric, and Personality Research. Illinois.  https://CRAN.R-project.org/package=psych  
Viechtbauer, W. (2010). Conducting meta-analyses in R with the metafor package. Journal of Statistical Software, 36(3), 1-48. https://doi.org/10.18637/jss.v036.i03  
Fisher Z, Tipton E, Zhipeng H (2023).robumeta: Robust Variance Meta-Regression. R package version 2.1. https://CRAN.R-project.org/package=robumeta



## Examples

```r
#Defining covariates for balance estimation
covariates_vector <- c("GPA_school", "IQ_score", "Motivation", "parents_academic", "sex")

#Computing initial unbalance for giftedness support
unbalance_gifted <- initial_unbalance(Data = MAGMA_sim_data,
group = "gifted_support",
covariates = covariates_vector)
unbalance_gifted

#Computing initial unbalnce for teacher rated ability
unbalance_tar <- initial_unbalance(Data = MAGMA_sim_data,
group = "teacher_ability_rating",
covariates = covariates_vector)
unbalance_tar

#Computing initial unbalnce for teacher rated ability
unbalance_2x2 <- initial_unbalance(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
covariates = covariates_vector)
unbalance_2x2
```


# MAGMA

MAGMA matching


## Description

This function conducts many group matching for 2 to 4 groups. It augments
 the original data set by relevant MAGMA variables. For details, see below.


## Usage

```r
MAGMA(Data, group, dist, cores = 1)
```


## Arguments

Argument      |Description
------------- |----------------
`Data`     |     A data frame or tibble containing at least your grouping and distance variable. Data needs to be specified in your environment.
`group`     |     A character specifying the name of your grouping variable in data. Note that MAGMA can only match your data for a maximum of 4 groups. For matching over two groups (e.g., 2x2 Design) is possible by specifying group as a character vector with a length of two. In this case each or the 2 grouping variables can only have two levels.
`dist`     |     A character specifying the name of your distance variable in data.
`cores`     |     An integer defining the number of cores used for parallel computation.


## Details

This function conducts nearest neighbor many group matching. It is
 applicable for 2 to 4 groups or a 2x2 Design. As output, this function
 augment your original data by the variables weight , step , distance ,
 and ID . Weight indicates whether a case was matched. Step specifies the
 iteration in which a case was matched. It also shows which cases were matched
 together. Distance indicates the mean difference within a match. Since
 matches with a lower distance are matched in an earlier iteration, step and
 distance are strongly correlated.
 This function has some CPU and RAM load. In most four group applications and
 three group applications with large sample size, RAM may be not sufficient.
 Therefore MAGMA switches to random quasi-systematic matching. If this is the
 case MAGMA informs you. Results does not change, but Balance might be
 slightly affected.


## Value

Your input data frame augmented with matching
 relevant variables, namely weight , step , distance , and ID . In case
 of missing values on the distance or group variable, MAGMA excludes them for
 the matching process. The returned data set does not contain those excluded
 cases. For more information, see Details.


## Author

Julian Urban


## Examples

```r
#Running this code will take a while
#Computing two-group Matching for giftedness support
MAGMA_sim_data_gifted<- MAGMA(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
cores = 2)
head(MAGMA_sim_data_gifted)

#Conducting three-group matching for teacher ability rating. Cores per
#default = 1
MAGMA_sim_data_tar <- MAGMA(Data = MAGMA_sim_data,
group = "teacher_ability_rating",
dist = "ps_tar")
head(MAGMA_sim_data_tar)

#Computing 2x2 Matching for giftedness support and enrichment equivalent to
#a four group matching
MAGMA_sim_data_gift_enrich <- MAGMA(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
dist = "ps_2x2",
cores = 2)
head(MAGMA_sim_data_gift_enrich)
```


# MAGMA_desc

MAGMA descriptive statistics


## Description

This function provides pre- and post matching descriptive statistics and
 effects.


## Usage

```r
MAGMA_desc(
  Data,
  covariates,
  group,
  step_num = NULL,
  step_var = NULL,
  filename = NULL
)
```


## Arguments

Argument      |Description
------------- |----------------
`Data`     |     A data frame that contains the desired variable for density plotting as well as the specified grouping variable.
`covariates`     |     A character vector naming the variable names of the continuous variables for that the descriptive statistics should be computed.
`group`     |     A character (vector) specifying the groups for which differentiated statistics should be computed.
`step_num`     |     Optional argument. If no value is specified, pre matching statistics are computed. For post matching statistics the exact needs to be defined via the step arguments. step_num is an integer specifying the number of cases that should be included per group in this post matching comparison. Is based on the step variable of MAGMA.
`step_var`     |     Optional argument. If no value is specified, pre matching statistics are computed. For post matching statistics the exact needs to be defined via the step arguments. A Character specifying the name of the step variable in the data set.
`filename`     |     Optional argument.  A character specifying the filename that the resulting Word document with the Table should have.


## Details

This function enables the computation of descriptive statistics of
 continuous variables for the overall sample and specified groups. Additional,
 pairwise effects (Cohen's d) is computed.


## Value

A table of descriptive statistics and pairwise effects for pre- or
 postmatching samples.


## Author

Julian Urban


## Examples

```r
#Defining covariates
covariates_gifted <- c("GPA_school", "IQ_score", "Motivation", "parents_academic", "sex")

#Estimating pre matching descriptive statistics and pairwise effects
MAGMA_desc(Data = MAGMA_sim_data,
covariates = covariates_gifted,
group =  "gifted_support")

#Matching the data for gifted support
MAGMA_sim_data_gifted <- MAGMA(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
cores = 2)

#Estimating post matching descriptive statistics and pairwise effects
MAGMA_desc(Data = MAGMA_sim_data_gifted,
covariates = covariates_gifted,
group =  "gifted_support"
step_num = 100,
step_var = "step")
```


# MAGMA_exact

MAGMA exact-matching


## Description

This function conducts exact many group matching for 2 to 4 groups. Exact
 means, that only cases with the same value on the exact variable can be
 matched. It augments the original data set by relevant MAGMA variables.
 For details, see below.


## Usage

```r
MAGMA_exact(Data, group, dist, exact, cores = 1)
```


## Arguments

Argument      |Description
------------- |----------------
`Data`     |     A data frame or tibble containing at least your grouping and distance variable. Data needs to be specified in your environment.
`group`     |     A character specifying the name of your grouping variable in data. Note that MAGMA can only match your data for a maximum of 4 groups. For matching over two groups (e.g., 2x2 Design) is possible by specifying group as a character vector with a length of two. In this case each or the 2 grouping variables can only have two levels.
`dist`     |     A character specifying the name of your distance variable in data.
`exact`     |     A character specifying the name of the exact variable. Only cases with the same value on this variable can be matched.
`cores`     |     An integer defining the number of cores used for parallel computation.


## Details

This function conducts nearest neighbor exact many group matching. It is
 applicable for 2 to 4 groups or a 2x2 Design. As output, this function
 augment your original data by the variables weight , step , distance ,
 and ID . Weight indicates whether a case was matched. Step specifies the
 iteration in which a case was matched. It also shows which cases were
 matched together. Distance indicates the mean difference within a match.
 Since matches with a lower distance are matched in an earlier iteration,
 step and distance are strongly correlated.
 Exact matching means that only cases with the same value on the exact
 variable can be matched. As example, only person of the same gender, the
 same school, or the same organization are possible matches. For standard
 matching, see [`MAGMA`](#magma)


## Value

Your input data frame of valid cases augmented with matching
 relevant variables, namely weight , step , distance , and ID . In case
 of missing values on the distance or group variable, MAGMA excludes them for
 the matching process. The returned data set does not contain those excluded
 cases. For more information, see Details.


## Author

Julian Urban


## Examples

```r
#Running this code will take a while
#Computing two-group Matching for giftedness support with exact for enrichment
MAGMA_sim_data_gifted_exact <- MAGMA_exact(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
exact = "enrichment",
cores = 2)
head(MAGMA_sim_data_gifted_exact)

#Conducting three-group matching for teacher ability rating exact for
#sex. Cores per default = 1
MAGMA_sim_data_tar_exact<- MAGMA_exact(Data = MAGMA_sim_data,
group = "teacher_ability_rating",
dist = "ps_tar",
exact = "sex")
head(MAGMA_sim_data_tar_exact)

#Computing 2x2 Matching for giftedness support and enrichment equivalent to
#a four group matching with exact MAGMA_exact for teacher rated ability
MAGMA_sim_data_gift_enrich_exact <- MAGMA_exact(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
dist = "ps_2x2",
exact = "teacher_ability_rating",
cores = 2)
head(MAGMA_sim_data_gift_enrich_exact)
```


# MAGMA_sim_data

MAGMA simulated data set


## Description

The MAGMA simulated data set contains 14 variables of 800 cases. It is used
 as example in the Vignette and the help pages.


## Format

A data frame with 14 variables of 800 cases.

## Usage

```r
MAGMA_sim_data
```


# Plot_MAGMA

Balance plots


## Description

Plots for Balance with respect to sample size.


## Usage

```r
Plot_MAGMA(
  Balance,
  criterion = c("Pillai", "d_ratio", "mean_g", "Adj_d_ratio")
)
```


## Arguments

Argument      |Description
------------- |----------------
`Balance`     |     A result of Balance_MAGMA. Compare the function [`Balance_MAGMA`](#balancemagma) .
`criterion`     |     A character vector specifying for which balance criteria a plot should be created. Default is all criteria.


## Details

This function creates R-Plots using ggplot to show the balance trend over
 sample size.


## Value

R Plots showing the balance trend over sample size.


## Author

Julian Urban


## Examples

```r
#This function bases on a MAGMA function as well as Balance_MAGMA.
#To run examples, copy them into your console or script.
#Defining the names of the metric and binary covariates
covariates_vector <- c("GPA_school", "IQ_score", "Motivation", "parents_academic", "sex")

#Matching data set for giftedness support with exact matching for enrichment.
MAGMA_sim_data_gifted_exact <- MAGMA_exact(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
exact = "enrichment",
cores = 2)


#Estimating Balance
Balance_gifted_exact <- Balance_MAGMA(Data = MAGMA_sim_data_gifted_exact,
group = "gifted_support",
covariates = covariates_vector,
step = "step") #step created during matching

Plot_MAGMA(Balance = Balance_gifted_exact) #Using default to plot all criteria

#Computing 2x2 Matching for giftedness support and enrichment equivalent to
#a four group matching
MAGMA_sim_data_gift_enrich <- MAGMA(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
dist = "ps_2x2",
cores = 2)


#Estimating Balance. Covariates same as above
Balance_2x2 <- Balance_MAGMA(Data = MAGMA_sim_data_gift_enrich,
group = c("gifted_support", "enrichment"),
covariates = covariates_vector,
step = "step") #step created during matching

Plot_MAGMA(Balance = Balance_2x2,
criterion = c("d_ration", "Adj_d_ratio"))
```


# Table_MAGMA

Balance table


## Description

This function prints an APA Table of the Balance criteria. It displays the
 balance criteria for four different sample sizes per group. In each scenario
 one balance criteria has its optimal value. Thus, the table is a 4x5 table
 showing the four balance criteria and the respective sample size per group
 for the four scenarios.


## Usage

```r
Table_MAGMA(Balance, filename = NULL)
```


## Arguments

Argument      |Description
------------- |----------------
`Balance`     |     A result of Balance_MAGMA. Compare the function [`Balance_MAGMA`](#balancemagma) .
`filename`     |     Optional argument.  A character specifying the filename that the resulting Word document with the Table should have.


## Details

This function creates an APA Table including the optimal models for each
 balance criterion, the other criteria for this sample size per group as well
 as the sample size itself. With an optional argument you can save a the APA
 table in Word.


## Value

A 4x5 APA Table showing the four balance
 criteria and the respective sample size per group for four scenarios. In
 each of these scenario one balance criteria has its optimal value. It can
 print a Word Document with this table, too.


## Author

Julian Urban


## Examples

```r
#This function bases on a MAGMA function as well as Balance_MAGMA.
#To run examples, copy them into your console or script.
#Defining the names of the metric and binary covariates
covariates_vector <- c("GPA_school", "IQ_score", "Motivation", "parents_academic", "sex")

#Matching data set for giftedness support with exact matching for enrichment.
MAGMA_sim_data_gifted_exact <- MAGMA_exact(Data = MAGMA_sim_data,
group = "gifted_support",
dist = "ps_gifted",
exact = "enrichment",
cores = 2)


#Estimating Balance
Balance_gifted_exact <- Balance_MAGMA(Data = MAGMA_sim_data_gifted_exact,
group = "gifted_support",
covariates = covariates_vector,
step = "step") #step created during matching

Table_MAGMA(Balance_gifted_exact, "Balance_gifted_exact.docx")

#Computing 2x2 Matching for giftedness support and enrichment equivalent to
#a four group matching
MAGMA_sim_data_gift_enrich <- MAGMA(Data = MAGMA_sim_data,
group = c("gifted_support", "enrichment"),
dist = "ps_2x2",
cores = 2)


#Estimating Balance. Covariates same as above
Balance_2x2 <- Balance_MAGMA(Data = MAGMA_sim_data_gift_enrich,
group = c("gifted_support", "enrichment"),
covariates = covariates_vector,
step = "step") #step created during matching

Table_MAGMA(Balance_2x2, "Balance_2x2.docx")
```
